import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { getCurrentUser } from '@/lib/getCurrentUser'
import UserStoreInitializer from '@/components/UserStoreInitializer'
import CoursesStoreInitializer from '@/components/CoursesStoreInitializer'
import { prisma } from '@/lib/prisma'

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = await getCurrentUser()
  const courses = await prisma.course.findMany({
		orderBy: { createdAt: 'desc' },
	})

  return (
    <html lang="en" className={cn("h-full", "antialiased", inter.variable, "font-sans")}>
      <body className="min-h-full flex flex-col font-sans">
        <UserStoreInitializer user={user} />
        <CoursesStoreInitializer courses={courses} />
        {children}
      </body>
    </html>
  );
}